//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodorderingsystem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("foodorderingsystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7b7d3efa61dc808d6f44d34e8a65af9c {
            get {
                object obj = ResourceManager.GetObject("7b7d3efa61dc808d6f44d34e8a65af9c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Back_Vector_Icon__Back_Icons__Back__Backward_PNG_and_Vector_with_Transparent_Background_for_Free_Download {
            get {
                object obj = ResourceManager.GetObject("Back Vector Icon, Back Icons, Back, Backward PNG and Vector with Transparent Back" +
                        "ground for Free Download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Baixar_ícone_de_vetor_de_feedback_gratuitamente {
            get {
                object obj = ResourceManager.GetObject("Baixar ícone de vetor de feedback gratuitamente", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Balance_check_icon {
            get {
                object obj = ResourceManager.GetObject("Balance check icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Balance_check_icon1 {
            get {
                object obj = ResourceManager.GetObject("Balance check icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Balance_check_icon2 {
            get {
                object obj = ResourceManager.GetObject("Balance check icon2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bank_iPhone_App_Icon {
            get {
                object obj = ResourceManager.GetObject("Bank iPhone App Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bixby_routines_brown_app_icon {
            get {
                object obj = ResourceManager.GetObject("bixby routines brown app icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Carraça_ícone_símbolo__marca_de_seleção__verificado_ícone_ou_corrigir_escolha_sinal__Verifica_marca_ou_caixa_de_seleção_pictograma {
            get {
                object obj = ResourceManager.GetObject("Carraça ícone símbolo, marca de seleção, verificado ícone ou corrigir escolha sin" +
                        "al, Verifica marca ou caixa de seleção pictograma", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Descargar_fondo_de_patrón_de_estilo_de_vida_de_comida_saludable_gratis {
            get {
                object obj = ResourceManager.GetObject("Descargar fondo de patrón de estilo de vida de comida saludable gratis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Descargar_fondo_de_patrón_de_estilo_de_vida_de_comida_saludable_gratis1 {
            get {
                object obj = ResourceManager.GetObject("Descargar fondo de patrón de estilo de vida de comida saludable gratis1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Descargar_fondo_de_patrón_de_estilo_de_vida_de_comida_saludable_gratis2 {
            get {
                object obj = ResourceManager.GetObject("Descargar fondo de patrón de estilo de vida de comida saludable gratis2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Descargar_fondo_de_patrón_de_estilo_de_vida_de_comida_saludable_gratis3 {
            get {
                object obj = ResourceManager.GetObject("Descargar fondo de patrón de estilo de vida de comida saludable gratis3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Descargar_fondo_de_patrón_de_estilo_de_vida_de_comida_saludable_gratis4 {
            get {
                object obj = ResourceManager.GetObject("Descargar fondo de patrón de estilo de vida de comida saludable gratis4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Descargar_fondo_de_patrón_de_estilo_de_vida_de_comida_saludable_gratis5 {
            get {
                object obj = ResourceManager.GetObject("Descargar fondo de patrón de estilo de vida de comida saludable gratis5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Descargar_fondo_de_patrón_de_estilo_de_vida_de_comida_saludable_gratis6 {
            get {
                object obj = ResourceManager.GetObject("Descargar fondo de patrón de estilo de vida de comida saludable gratis6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Descargar_fondo_de_patrón_de_estilo_de_vida_de_comida_saludable_gratis7 {
            get {
                object obj = ResourceManager.GetObject("Descargar fondo de patrón de estilo de vida de comida saludable gratis7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Descargar_fondo_de_patrón_de_estilo_de_vida_de_comida_saludable_gratis8 {
            get {
                object obj = ResourceManager.GetObject("Descargar fondo de patrón de estilo de vida de comida saludable gratis8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Descargar_fondo_de_patrón_de_estilo_de_vida_de_comida_saludable_gratis9 {
            get {
                object obj = ResourceManager.GetObject("Descargar fondo de patrón de estilo de vida de comida saludable gratis9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dessert {
            get {
                object obj = ResourceManager.GetObject("Dessert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__1_ {
            get {
                object obj = ResourceManager.GetObject("download (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__2_ {
            get {
                object obj = ResourceManager.GetObject("download (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__4_ {
            get {
                object obj = ResourceManager.GetObject("download (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__5_ {
            get {
                object obj = ResourceManager.GetObject("download (5)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__6_ {
            get {
                object obj = ResourceManager.GetObject("download (6)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fresh_vegetables_photo {
            get {
                object obj = ResourceManager.GetObject("fresh-vegetables-photo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fresh_vegetables_photo1 {
            get {
                object obj = ResourceManager.GetObject("fresh-vegetables-photo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Group_Of_Fast_Food_Products__Fast_Food_Products__Group_Of_Fast_Food__Fast_Food_PNG_Transparent_Image_and_Clipart_for_Free_Download {
            get {
                object obj = ResourceManager.GetObject("Group Of Fast Food Products, Fast Food Products, Group Of Fast Food, Fast Food PN" +
                        "G Transparent Image and Clipart for Free Download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Group_Of_Fast_Food_Products__Fast_Food_Products__Group_Of_Fast_Food__Fast_Food_PNG_Transparent_Image_and_Clipart_for_Free_Download1 {
            get {
                object obj = ResourceManager.GetObject("Group Of Fast Food Products, Fast Food Products, Group Of Fast Food, Fast Food PN" +
                        "G Transparent Image and Clipart for Free Download1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Group_Of_Fast_Food_Products__Fast_Food_Products__Group_Of_Fast_Food__Fast_Food_PNG_Transparent_Image_and_Clipart_for_Free_Download2 {
            get {
                object obj = ResourceManager.GetObject("Group Of Fast Food Products, Fast Food Products, Group Of Fast Food, Fast Food PN" +
                        "G Transparent Image and Clipart for Free Download2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Herbs_and_condiments_stock_photo_containing_above_and_aromatic {
            get {
                object obj = ResourceManager.GetObject("Herbs and condiments stock photo containing above and aromatic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Italians_Dish {
            get {
                object obj = ResourceManager.GetObject("Italians Dish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Maxican_Feast {
            get {
                object obj = ResourceManager.GetObject("Maxican Feast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Menu_and_restaurant_icons_design_vector_illustration {
            get {
                object obj = ResourceManager.GetObject("Menu and restaurant icons design vector illustration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ordering_Food_Online_stock_vector__Illustration_of_internet___47035249 {
            get {
                object obj = ResourceManager.GetObject("Ordering Food Online stock vector_ Illustration of internet - 47035249", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Shopping_cart_Animated_Icon___Free_commerce_Animated_Icon {
            get {
                object obj = ResourceManager.GetObject("Shopping cart Animated Icon _ Free commerce Animated Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shopping_light_brown_icon_app_ios14 {
            get {
                object obj = ResourceManager.GetObject("shopping light brown icon app ios14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap вектор_икона_PNG___значки_меню__список__Линия_PNG_картинки_и_пнг_рисунок_для_бесплатной_загрузки {
            get {
                object obj = ResourceManager.GetObject("вектор икона PNG , значки меню, список, Линия PNG картинки и пнг рисунок для бесп" +
                        "латной загрузки", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
